<?php

return [
    'templates' => [
        'page-builder' => [
            'name' => 'Page Builder / Blank Canvas',
            'description' => 'หน้าเปล่าสำหรับประกอบด้วย block จาก Page Builder',
            'template_type' => 'page',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.pages.builder',
            'is_default' => true,
            'sort_order' => 1,
        ],
        'page-default' => [
            'name' => 'Generic Page Default',
            'description' => 'หน้า default แบบ fallback สำหรับข้อมูลหน้าแบบเดิม',
            'template_type' => 'page',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.pages.default',
            'is_default' => false,
            'sort_order' => 10,
        ],
        'home-default' => [
            'name' => 'Home Default',
            'description' => 'Homepage template เดิม รองรับ Page Builder เมื่อมี block',
            'template_type' => 'page',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.pages.home-default',
            'is_default' => false,
            'sort_order' => 20,
        ],
        'home-focus' => [
            'name' => 'Home Focus',
            'description' => 'Homepage focus template เดิม รองรับ Page Builder เมื่อมี block',
            'template_type' => 'page',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.pages.home-focus',
            'is_default' => false,
            'sort_order' => 21,
        ],
        'home-split' => [
            'name' => 'Home Split',
            'description' => 'Homepage split template เดิม รองรับ Page Builder เมื่อมี block',
            'template_type' => 'page',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.pages.home-split',
            'is_default' => false,
            'sort_order' => 22,
        ],
        'listing-page' => [
            'name' => 'Generic Listing Page',
            'description' => 'Template รายการทั่วไป',
            'template_type' => 'list',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.pages.listing',
            'is_default' => false,
            'sort_order' => 30,
        ],
        'temple-list' => [
            'name' => 'Temple List',
            'description' => 'หน้า list วัด รองรับ block หน้ารวมวัด',
            'template_type' => 'list',
            'content_type' => 'temple',
            'view_path' => 'frontend.templates.lists.temple-list',
            'is_default' => false,
            'sort_order' => 40,
        ],
        'article-list' => [
            'name' => 'Article List',
            'description' => 'หน้า list บทความ รองรับ block หน้ารวมบทความ',
            'template_type' => 'list',
            'content_type' => 'article',
            'view_path' => 'frontend.templates.lists.article-list',
            'is_default' => false,
            'sort_order' => 41,
        ],
        'temple-detail' => [
            'name' => 'Temple Detail Default',
            'description' => 'Template หลักสำหรับหน้าแสดงรายละเอียดวัด',
            'template_type' => 'detail',
            'content_type' => 'temple',
            'view_path' => 'frontend.templates.details.temple-default',
            'is_default' => true,
            'sort_order' => 50,
        ],
        'temple-compact-detail' => [
            'name' => 'Temple Detail Compact',
            'description' => 'Template รายละเอียดวัดแบบ compact',
            'template_type' => 'detail',
            'content_type' => 'temple',
            'view_path' => 'frontend.templates.details.temple-compact',
            'is_default' => false,
            'sort_order' => 51,
        ],
        'article-detail' => [
            'name' => 'Article Detail Default',
            'description' => 'Template หลักสำหรับหน้าแสดงรายละเอียดบทความ',
            'template_type' => 'detail',
            'content_type' => 'article',
            'view_path' => 'frontend.templates.details.article-default',
            'is_default' => true,
            'sort_order' => 60,
        ],
        'article-editorial-detail' => [
            'name' => 'Article Detail Editorial',
            'description' => 'Template บทความแบบ editorial',
            'template_type' => 'detail',
            'content_type' => 'article',
            'view_path' => 'frontend.templates.details.article-editorial',
            'is_default' => false,
            'sort_order' => 61,
        ],
        'admin-preview-safe' => [
            'name' => 'Admin Preview Safe',
            'description' => 'Template สำหรับ fallback preview ใน iframe ของ admin',
            'template_type' => 'page',
            'content_type' => 'global',
            'view_path' => 'frontend.templates.previews.admin-iframe',
            'is_default' => false,
            'sort_order' => 90,
        ],
    ],

    'sections' => [
        'hero' => [
            'label' => 'Hero',
            'content_required' => ['title'],
        ],
        'banner' => [
            'label' => 'Banner',
            'content_required' => ['title'],
        ],
        'rich_text' => [
            'label' => 'Rich text',
            'content_required' => ['title', 'body'],
        ],
        'image_text' => [
            'label' => 'Image with text',
            'content_required' => ['title'],
        ],
        'cta' => [
            'label' => 'Call to action',
            'content_required' => ['title'],
            'cta' => true,
        ],
        'article_grid' => ['label' => 'Article grid', 'content_required' => []],
        'temple_grid' => ['label' => 'Temple grid', 'content_required' => []],
        'travel_discovery_bento' => ['label' => 'Travel discovery bento', 'content_required' => []],
        'favorites_list' => ['label' => 'Favorites list', 'content_required' => []],
        'article_list_full' => ['label' => 'Article list full', 'content_required' => []],
        'temple_list_full' => ['label' => 'Temple list full', 'content_required' => []],
        'gallery' => ['label' => 'Gallery', 'content_required' => []],
        'faq' => ['label' => 'FAQ', 'content_required' => []],
        'stats' => ['label' => 'Stats', 'content_required' => []],
        'contact' => ['label' => 'Contact', 'content_required' => []],
    ],
];
